apiVersion: v1
kind: Service
metadata:
  creationTimestamp: '2018-06-25T16:58:16Z'
  labels:
    app: assessment
  name: assessment
  namespace: arquitetura
  resourceVersion: '10232535'

  uid: f437bb95-7898-11e8-8c93-42010a8e0002
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deploymentconfig: assessment
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
