spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create


  h2:
    console:
      enabled: true
      path: /console