spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:file:~/assesment;DB_CLOSE_ON_EXIT=FALSE


  h2:
    console:
      enabled: true
      path: /console